server:
  port: 8081

spring:
  application:
    name: UserService

  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/subscription_users
    username: postgres
    password: "0000"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
      leak-detection-threshold: 5000

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:     # Gmail app password yazın
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        transport:
          protocol: smtp

  # Redis Configuration
  #  data:
  #    redis:
  #      host: localhost
  #      port: 6379
  #      timeout: 2000ms
  #      lettuce:
  #        pool:
  #          max-active: 8
  #          max-idle: 8
  #          min-idle: 0

  # Actuator Configuration
  main:
    allow-bean-definition-overriding: false

# JWT Configuration
jwt:
  secret: mySecretKey123456789012345678901234567890
  access-token:
    expiration: 900000 # 15 minutes
  refresh-token:
    expiration: 604800000 # 7 days

email:
  template:
    welcome:
      subject: "Welcome - Your registration has been completed successfully"
    profile-update:
      subject: "Your profile information has been updated"
    admin-promotion:
      subject: "Admin privileges granted"

# Logging Configuration
logging:
  level:
    com.example.userservice: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized